### PR TITLE
add dark mode

### PR DESCRIPTION
**Pull request by DerMistkaefer**
Please spare my eyes and finally give me dark mode!
We use the system-specific preferred color mode.

White Mode:
image

Dark Mode:
image

### CODE REVIEW

**Review by florianreuth — APPROVED** [review]
10/10, changed my life!

**Review by RealBauHD — APPROVED** [review]

**Review by RealBauHD — APPROVED** [review]
My eyes thank you!

**Comment by DerMistkaefer** [comment]
Changed also the diagram grid to dark mode
image

**Review by florianreuth — APPROVED** [review]

**Review by RealBauHD — APPROVED** [review]
even better

**Review by kennytv — APPROVED** [review]

**Pull request merged**
